#!/bin/bash
set -x


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
#ENDORSE_SRC_ROOT="$SCRIPT_DIR/../.."

source $SCRIPT_DIR/load_modules


# Name of the virtual environment folder
VENV_DIR="$SCRIPT_DIR/venv"

if [ "$1" == "-d" ];
then
    rm -rf "$VENV_DIR"
fi


# Check if virtual environment directory already exists
if [ -d "$VENV_DIR" ]; then
    echo "Virtual environment already exists."
else
    # Create a virtual environment
    python3 -m venv $VENV_DIR
    echo "Virtual environment created."
fi

# Activate the virtual environment
source $VENV_DIR/bin/activate
echo "Virtual environment activated."

# Install dependencies from requirements.txt if the file exists
if [ -f "requirements.txt" ]; then
    python3 -m pip install --upgrade pip
    python3 -m pip install -r requirements.txt
    echo "Dependencies installed from requirements.txt."
else
    echo "requirements.txt not found. Skipping dependency installation."
fi

# check git submodules
#git submodule update --init --recursive
# install necessary submodules
#pip install --no-cache-dir -e ${ENDORSE_SRC_ROOT}/submodules/bgem

# install endorse
#pip install -e ${ENDORSE_SRC_ROOT}
#pip install -e ${SCRIPT_DIR}

# REgister as a Jupyter kernel
#python3 -m ipykernel install --user --name=hlavo_env --display-name "Hlavo Environment"

# Install custom tinyDA
#$SCRIPT_DIR/docker/install_custom_tinyda.sh $VENV_DIR/ tinyDA/
