# base of the mesh file name
mesh_name: trans_mesh

mesh:
    # mesh step on outer boundary
    boundary_mesh_step: 20

    main_tunnel_mesh_step: 1

    # refinement around central line of main tunnel
    main_line_refinement:
      r_inner: 2
      h_inner: 1.5
      r_outer: 10
      h_outer: 1.5
      q_outer: 1
      r_inf: 30
      h_inf: 10

geometry:
  # Coordinate system
  # X - in direction of main tunnel
  # Y - perpendicular horizontal
  # Z - vertical
  # origin: floor of the lateral tunnel, center, interface with center borehole.

  # x,y,z dimension
  box_dimensions: &box [40, 72, 40]



  # Main tunnel - main access tunnel L5
  main_tunnel:
    csv_points: main_tunnel_points.csv
    height: 4
    width: 4
    length: 72

  storage_borehole_distance: 12
  n_storage_boroholes: 5
  damaged_storage_borehole: 2

  # Storage boreholes
  storage_borehole:
    radius: 0.6
    length: 6
    plug: 2
    mesh_step: 0.25

  storage_borehole_refinement:
    r_inner: 0.2
    h_inner: 0.2
    r_outer: 1.2
    h_outer: 0.6
    q_outer: 1
    r_inf: 30
    h_inf: 10
