# Coordinate system
# X - in direction of main tunnel
# Y - perpendicular horizontal
# Z - vertical
# origin: floor of the lateral tunnel, center, interface with center borehole.

# x,y,z dimension
box_dimensions: &box [40, 40, 40]
clip_box_dimensions: [40, 40, 40]

edz_radius: 2.5

include: #[]
  - boreholes
  - fractures
  - drilled_volume

# Main tunnel - main access tunnel L5
main_tunnel:
  csv_points: main_tunnel_points.csv
  height: 6.700
  width: 4
  length: 40
  center: [0,0,0] # to be filled automatically as center of csv_points

storage_borehole_distance: 4.750
n_storage_boroholes: 5
damaged_storage_borehole: 2  # can be negative => no damaged container

# Storage boreholes
storage_borehole:
  diameter: 1.650
  length: 6.540
  plug: 2.000
  mesh_step: 0.25
