# base of the mesh file name
mesh_name: trans_mesh

geometry: &geometry !include _geometry.yaml

mesh:
    # mesh step on outer boundary
    boundary_mesh_step: &boundary_mesh_step 15
    fracture_mesh_step: 4
    main_tunnel_mesh_step: 1

    # refinement around central line of main tunnel
    main_line_refinement:
      r_inner: 2
      h_inner: 0.5
      r_outer: 10
      h_outer: 1.5
      q_outer: 1
      r_inf: 30
      h_inf: *boundary_mesh_step

    storage_borehole_refinement:
      r_inner: 0.2
      h_inner: 0.2
      r_outer: 1.2
      h_outer: 0.6
      q_outer: 1
      r_inf: 30
      h_inf: *boundary_mesh_step

fractures: &fractures
    # SKB fracture population for repository domain
    population:  !include _fractures.yaml
    # upper limit on the number of (small) fractures
    n_frac_limit: 100

    # Experiments for large fr range [50, 200] and large_box: [20,20,20]
    # most seeds have no large fracture at all
    # probability of  50 m fracture near borehole is about,
    #  1 fracture per 1km of borehole
    #  crossing borehole: 3 fracture per 10 km
    fixed_seed: 202  # in the middle, acute angle , not reaching boundary

    large_min_r: 100
    large_box:  [60, 60, 60]
    # Would be better to have separate domains for known large fractures close to tunnel and
    # uncertain large fractures, need support in Population
    # main box : [100, 80, 60]



