# base of the mesh file name
mesh_name: trans_mesh

geometry: &geometry !include _geometry.yaml

mesh:
    # mesh step on outer boundary
    boundary_mesh_step: &boundary_mesh_step 15
    fracture_mesh_step: 4
    main_tunnel_mesh_step: 1

    # refinement around central line of main tunnel
    main_line_refinement:
      r_inner: 2
      h_inner: 0.5
      r_outer: 10
      h_outer: 1.5
      q_outer: 1
      r_inf: 30
      h_inf: *boundary_mesh_step

    storage_borehole_refinement:
      r_inner: 0.2
      h_inner: 0.2
      r_outer: 1.2
      h_outer: 0.6
      q_outer: 1
      r_inf: 30
      h_inf: *boundary_mesh_step

fractures: &fractures
    # SKB fracture population for repository domain
    population:  !include _fr_Forsmark_repo.yaml
    # upper limit on the number of (small) fractures
    n_frac_limit: 100

    # Experiments for large fr range [50, 200] and large_box: [20,20,20]
    # most seeds have no large fracture at all
    # probability of  50 m fracture near borehole is about,
    #  1 fracture per 1km of borehole
    #  crossing borehole: 3 fracture per 10 km
    fixed_seed: 202  # in the middle, acute angle , not reaching boundary

    large_min_r: 100
    large_box:  [60, 60, 60]
    # Would be better to have separate domains for known large fractures close to tunnel and
    # uncertain large fractures, need support in Population
    # main box : [100, 80, 60]

bulk_field_parametric: &bulk_field_parametric
    cond_zero: 1e-16
    cond_max: 1e-8  # increased edz 10 times higher then for TSX (try to make EDZ significant)
    cond_min: 3e-13  # 3x higher than TSX (1e-13), mean transport time should be about 100 ky   to fracture conductivities,
    por_max: 0.0025
    por_min: 0.002

    # values with respect to EDZ radius
    h_axis: 2 #1.5
    v_axis: 2
    # radius for c_min
    inner_radius: 1.0 # 1.1

# parameters substituted into the TH model template
transport_fullscale:
    geometry: *geometry
    fractures: *fractures
    # The mesh to use in both simulations.

    # templates are part of the endorse sources
    input_template: transport_fullscale_tmpl.yaml

    # relative to main config
    piezo_head_input_file: "large_model_local.msh2"
    conc_flux_file: "conc_flux_UOS_kg_y.csv"
    conc_name: I
    mesh:
        # mesh step on fractures
        fracture_mesh_step: 10
        # mesh step on outer boundary
        boundary_mesh_step: 50
        # mesh step on outer boundary of EDZ (just around boreholes right now)
        edz_mesh_step: 1
        # mesh step on inner boreholes
        boreholes_mesh_step: 0.3   # haxagon boreholes
        #boreholes_mesh_step: 0.3   # EDZ minimal resolution
        main_tunnel_mesh_step: 2

    bulk_field_params: *bulk_field_parametric
    fr_field_params:
        apperture_per_size: 1e-5  # 1e-4 = 1mm na 10m
        #fr_conductivity: 2.5e-3     # k = 1/12 * cs^2 * rho*g/visc = 1/12 1e-8 * 1000*10*1e3 =approx. 1e-2 ; cs=1e-4
        permeability_factor: 1e-2      # relative permeability with respect to ideal case given by cubic law
        #sigma_bulk_conductivity: 1e-7
        #min_fr_cross_section: 5e-5
        #max_fr_cross_section: 5e-3

    #diffusivity_effective: 1e-13     # 2e-12 for I, according to SKB 97-20
    #diffusivity_effective: 3e-14     # řádově spodní mez pro Cs a Sr, horní pro I podle SURAO TZ334
    diffusivity_effective: 1e-15    # should be smaller then advection
    dispersivity_L: 1    # [m]
    dispersivity_T: 0.1     # [m]
    #dispersivity_L: 0    # [m]
    #dispersivity_T: 0     # [m]
    dg_penalty: 10




    # setup for point source
    # TODO: max source search, use P0 approximation with space refinement spacing
    source_params:
        source_ipos: 2 # ith position of the leaking container from beginning of the borehole
        source_length: 4 # length of the container [m]
        source_space: 2


    # The total simulation time as well as the output times are ese are quite dependent on the
    output_times:
      - 30
      - 60
      - 120
      - 240
      - 500
      - 1100
      - 2300
      - 5000
      - 10000
      - [20000, 20000]
    end_time: 160000

    flow_solver__a_tol: 1e-15
    flow_solver__r_tol: 1e-20
    #flow_solver__options:


    trans_solver__a_tol: 1e-15
    trans_solver__r_tol: 1e-8
        # -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg
#        # Boomeramg options:
#        # -ksp_type richardson              - recomended usage when solving just by multigrid
#        #  -pc_hypre_boomeramg_cycle_type <V> Cycle type (choose one of) V W (None)
#        #                                 cans try: V, W
#        #  -pc_hypre_boomeramg_max_levels <25>: Number of levels (of grids) allowed (None)
#        #  -pc_hypre_boomeramg_max_iter <1>: Maximum iterations used PER hypre call (None)
#        #                                  PETSC recomend more then 1 when just richardson KSP is used
#        #  -pc_hypre_boomeramg_tol <0.>: Convergence tolerance PER hypre call (0.0 = use a fixed number of iterations) (None)
#        #                                  PETSC says 1e-7 is default, when previous is not set
#        #  -pc_hypre_boomeramg_strong_threshold <0.25>: Threshold for being strongly connected (None)
#        #                                  HYPRE recommends 0.5 for 3d problems
#        #
#        #  -pc_hypre_boomeramg_P_max <0>: Max elements per row for interpolation operator (0=unlimited) (None)
#        #  -pc_hypre_boomeramg_agg_nl <0>: Number of levels of aggressive coarsening (None)
#        #  -pc_hypre_boomeramg_agg_num_paths <1>: Number of paths for aggressive coarsening (None)
#        #  -pc_hypre_boomeramg_strong_threshold <0.25>: Threshold for being strongly connected (None)
#        #  -pc_hypre_boomeramg_coarsen_type <Falgout> Coarsen type (choose one of) CLJP Ruge-Stueben  modifiedRuge-Stueben   Falgout  PMIS  HMIS (None)
#        #  -pc_hypre_boomeramg_interp_type <classical> Interpolation type (choose one of) classical   direct multipass multipass-wts ext+i ext+i-cc standard standard-wts block block-wtd FF FF1 (None)
#
#        #  -pc_hypre_boomeramg_relax_type_all <symmetric-SOR/Jacobi> Relax type for the up and down cycles (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
#        #  -pc_hypre_boomeramg_relax_type_down <symmetric-SOR/Jacobi> Relax type for the down cycles (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
#        #  -pc_hypre_boomeramg_relax_type_up <symmetric-SOR/Jacobi> Relax type for the up cycles (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
#        #  -pc_hypre_boomeramg_relax_type_coarse <Gaussian-elimination> Relax type on coarse grid (choose one of) Jacobi sequential-Gauss-Seidel seqboundary-Gauss-Seidel SOR/Jacobi backward-SOR/Jacobi  symmetric-SOR/Jacobi  l1scaled-SOR/Jacobi Gaussian-elimination      CG Chebyshev FCF-Jacobi l1scaled-Jacobi (None)
#        #  -pc_hypre_boomeramg_relax_weight_all <1.>: Relaxation weight for all levels (0 = hypre estimates, -k = determined with k CG steps) (None)
#        #  -pc_hypre_boomeramg_relax_weight_level <1.>: Set the relaxation weight for a particular level (weight,level) (None)
#        #  -pc_hypre_boomeramg_outer_relax_weight_all <1.>: Outer relaxation weight for all levels (-k = determined with k CG steps) (None)
#        #  -pc_hypre_boomeramg_outer_relax_weight_level <1.>: Set the outer relaxation weight for a particular level (weight,level) (None)
#        #  -pc_hypre_boomeramg_no_CF: <FALSE> Do not use CF-relaxation (None)
#
#
#        # -pc_hypre_boomeramg_max_iter <1>  - number of V/W cycles
#        # -pc_hypre_boomeramg_tol <1e-7>    - tolerance of MG solver
#        # -pc_hypre_boomeramg_coarsen_type  [PMIS  HMIS]  - recomenden for 3d problems
#        # -pc_hypre_boomeramg_interp_type [ext+i ext+i-cc] - probably recomended for 3d problems
#        # -pc_hypre_boomeramg_strong_threshold <0.5> - recomended for 3d problems
#        # for cg one must use symmetric smoother (default is hybrid Gauss-Siedel)
#        # options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg
#
#        # Experiements:
#        # options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg
#        # it: 421 r_tol 1e-7
#        #options: -ksp_type gmres -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5 -ksp_monitor
#        # it: 696 r_tol 1e-7
#        #opti

    #heat_solver__options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor
    # faild fo indef PC
    #heat_solver__options: -ksp_type gmres -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type PMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor
    # failed do to 1000 iterations
    # heat_solver__options: -ksp_type preonly -pc_type lu -pc_factor_mat_solver_type mumps
    # out of memory 12GB
    #trans_solver__options: -ksp_type gmres -pc_type ilu -pc_factor_levels 3 -ksp_diagonal_scale -ksp_diagonal_scale_fix -pc_factor_fill 1.0 -ksp_monitor

  # edz_phys_group: 77
